CREATE TABLE IF NOT EXISTS `talent_tab` (
	`ID` INT(10) NOT NULL,
	`Name` TEXT,
	`BackgroundFile` TEXT,
	`OrderIndex` INT(11) NOT NULL,
	`RaceMask` INT(11) NOT NULL,
	`ClassMask` INT(11) NOT NULL,
	`VerifiedBuild` INT(11) NOT NULL,
	PRIMARY KEY (`ID`, `VerifiedBuild`)
);

CREATE TABLE IF NOT EXISTS `talent_tab_locale` (
	`ID` INT(10) NOT NULL,
	`locale` VARCHAR(4) NOT NULL,
	`Name_lang` TEXT,
	`VerifiedBuild` INT(11) NOT NULL,
	PRIMARY KEY (`ID`, `locale`, `VerifiedBuild`)
);

-- Table drops
DROP TABLE IF EXISTS `achievement`,
    `achievement_locale`,
    `achievement_category`,
    `achievement_category_locale`,
    `adventure_journal`,
    `adventure_journal_locale`,
    `adventure_map_poi`,
    `adventure_map_po_locale`,
	`armor_location`,
	`artifact`,
	`artifact_locale`,
	`artifact_appearance`,
	`artifact_appearance_locale`,
	`artifact_appearance_set`,
	`artifact_appearance_set_locale`,
	`artifact_category`,
	`artifact_power`,
	`artifact_power_link`,
	`artifact_power_picker`,
	`artifact_power_rank`,
	`artifact_quest_xp`,
	`artifact_tier`,
	`artifact_unlock`,
	`azerite_essence`,
	`azerite_essence_locale`,
	`azerite_essence_power`,
	`azerite_essence_power_locale`,
	`azerite_item`,
	`azerite_item_milestone_power`,
	`azerite_knowledge_multiplier`,
	`azerite_level_info`,
	`azerite_power`,
	`azerite_power_set_member`,
	`azerite_tier_unlock`,
	`azerite_tier_unlock_set`,
	`azerite_unlock_mapping`,
	`barber_shop_style`,
	`barber_shop_style_locale`,
	`battle_pet_breed_quality`,
	`battle_pet_breed_state`,
	`battle_pet_species`,
	`battle_pet_species_locale`,
	`battle_pet_species_state`,
	`broadcast_text`,
	`broadcast_text_locale`,
	`chr_class_ui_display`,
	`chr_customization_display_info`,
	`chr_customization_req_choice`,
	`chr_specialization`,
	`chr_specialization_locale`,
	`content_tuning_x_expected`.
	`conversation_line`,
	`corruption_effects`,
	`destructible_model_data`,
	`expected_stat`,
	`expected_stat_mod`,
	`friendship_rep_reaction`,
	`friendship_rep_reaction_locale`,
	`friendship_reputation`,
	`friendship_reputation_locale`,
	`garr_ability`,
	`garr_ability_locale`.
	`garr_building`,
	`garr_building_locale`,
	`garr_building_plot_inst`,
	`garr_class_spec`,
	`garr_class_spec_locale`,
	`garr_follower`,
	`garr_follower_locale`,
	`garr_follower_x_quality`,
	`garr_plot`,
	`garr_plot_building`,
	`garr_plot_instance`,
	`garr_site_level`,
	`garr_site_level_plot_inst`,
	`global_curve`,
	`glyph_bindable_spell`,
	`glyph_properties`,
	`glyph_required_spec`,
	`guild_color_background`,
	`guild_color_border`,
	`guild_color_emblem`,
	`guild_perk_spells`,
	`heirloom`,
	`heirloom_locale`,
	`item_armor_quality`,
	`item_armor_shield`,
	`item_armor_total`,
	`item_bag_family`,
	`item_bag_family_locale`,
	`item_bonus`,
	`item_bonus_list_level_delta`,
	`item_bonus_tree_node`,
	`item_child_equipment`,
	`item_level_selector`,
	`item_level_selector_quality`,
	`item_level_selector_quality_set`,
	`item_limit_category_condition`,
	`item_modified_appearance_extra`,
	`item_name_description`,
	`item_name_description_locale`,
	`item_search_name`,
	`item_search_name_locale`,
	`item_spec`,
	`item_spec_override`,
	`item_x_bonus_tree`,
	`mount`,
	`mount_locale`,
	`mount_capability`,
	`mount_type_x_capability`,
	`mount_x_display`,
	`num_talents_at_level`,
	`override_spell_data`,
	`paragon_reputation`,
	`power_display`,
	`prestige_level_info`,
	`prestige_level_info_locale`,
	`pvp_item`,
	`pvp_talent`,
	`pvp_talent_locale`,
	`pvp_talent_category`,
	`pvp_tier`,
	`pvp_tier_locale`,
	`quest_line_x_quest`,
	`quest_package_item`,
	`reward_pack`,
	`reward_pack_x_currency_type`,
	`reward_pack_x_item`,
	`scenario`,
	`scenario_locale`,
	`scenario_step`,
	`scenario_step_locale`,
	`scene_script`,
	`scene_script_global_text`,
	`scene_script_package`,
	`scene_script_text`,
	`specialization_spells`,
	`specialization_spells_locale`,
	`spec_set_member`,
	`spell_learn_spell`,
	`spell_power_difficulty`,
	`spell_procs_per_minute`,
	`spell_procs_per_minute_mod`,
	`spell_scaling`,
	`toy`,
	`toy_locale`,
	`transmog_holiday`,
	`transmog_illusion`,
	`transmog_set`,
	`transmog_set_locale`,
	`transmog_set_group`,
	`transmog_set_group_locale`,
	`transmog_set_item`,
	`transport_rotation`,
	`unit_power_bar`,
	`unit_power_bar_locale`,
	`vehicle`,
	`vehicle_seat`;
